### ISSUE TITLE
CTD on end of turn

### ISSUE THREAD

**Issue by iamlags77** [We-the-People-civ4col-mod/Mod#662]
Hey all, amazing mod and I'm really enjoying it, thanks for your hard work.

I've hit a snag in my most recent game, I'm getting a consistent CTD during the end of turn AI sequence. 

Attached is the save file.

THANKS!

[paull AD-1600-April.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/10152652/paull.AD-1600-April.zip)

**Comment by raystuttgart** [comment]
Which version do you play?
The last public release 3.0.1?

**Comment by iamlags77** [comment]
yeah 3.0.1 

But I play on steam and only reverted my steam version once I encountered the bug.

**Comment by raystuttgart** [comment]
The good news is that the CTD you reported most likely already is fixed in internal 4.0 (aka "New Hope").
"New Hope" is about 2 years more advanced than 3.01. it is just not yet published ...

**Comment by iamlags77** [comment]
sorry is there a thread somewhere on how to run new hope? My next game also encountered a EOT CTD so I was hoping to run that version instead.

I dropped the DLLs into the exe folder (as per the branch readme) but still getting lots of errors on mod load so I must be missing a step.

**Comment by raystuttgart** [comment]
Ok I think this can be closed, since it is from old 3.0.1 and thus very likely to be fixed in "New Hope".
There is little point in tryign to reproduce bugs from a version that is already 2 years old.
